name: build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: webfactory/ssh-agent@v0.5.3
        with:
           ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Execute the build
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          .github/build.sh
