name: build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: webfactory/ssh-agent@v0.5.3
        with:
           ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Configure GitHub settings
        run: |
          git config --local user.email "ci@scijava.org"
          git config --local user.name "SciJava CI"
          
      - name: Execute the build
        run: .github/build.sh
